### ISSUE TITLE
Device boots but pwnagotchi service restarts

### ISSUE THREAD

**Issue by chermax14** [jayofelony/pwnagotchi#100]
pwnagotchi service restarts after updating to 2.8.7.1

jvm4c@jvm4c:~ $ sudo pwnagotchi --clear
INFO:root:[update] plugin loaded.
INFO:root:WIGLE: ready
[2024-03-18 10:27:34,754] [INFO] [update] plugin loaded.
INFO:root:[Fix_Services] plugin loaded.
INFO:root:[Wpa-sec-list] plugin loaded
[2024-03-18 10:27:34,755] [INFO] WIGLE: ready
INFO:root:WPA_SEC: plugin loaded
INFO:root:Session-stats plugin loaded.
INFO:root:grid plugin loaded.
[2024-03-18 10:27:34,758] [INFO] [Fix_Services] plugin loaded.
[2024-03-18 10:27:34,759] [INFO] [Wpa-sec-list] plugin loaded
[2024-03-18 10:27:34,762] [INFO] grid plugin loaded.
INFO:root:memtemp plugin loaded.
[2024-03-18 10:27:34,761] [INFO] Session-stats plugin loaded.
[2024-03-18 10:27:34,760] [INFO] WPA_SEC: plugin loaded
INFO:root:webcfg: Plugin loaded.
[2024-03-18 10:27:34,763] [INFO] memtemp plugin loaded.
[2024-03-18 10:27:34,764] [INFO] webcfg: Plugin loaded.
INFO:root:initializing waveshare v2in13_V4 display
[2024-03-18 10:27:34,791] [INFO] initializing waveshare v2in13_V4 display
INFO:root:BT-TETHER: Successfully loaded ...
[2024-03-18 10:27:34,854] [INFO] BT-TETHER: Successfully loaded ...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
          ~~~~~~~~~^^^^^^
KeyError: PinInfo(number=11, name='GPIO17', names=frozenset({'J8:11', 17, 'WPI0', 'BOARD11', 'GPIO17', 'BCM17', '17'}), pull='', row=6, col=1, interfaces=frozenset({'', 'dpi', 'gpio', 'uart', 'spi'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 338, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 318, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 240, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare2in13_V4.py", line 35, in initialize
    from pwnagotchi.ui.hw.libs.waveshare.v2in13_V4.epd2in13_V4 import EPD
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v2in13_V4/epd2in13_V4.py", line 32, in <module>
    from .. import epdconfig
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/epdconfig.py", line 127, in <module>
    implementation = RaspberryPi()
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/epdconfig.py", line 52, in __init__
    self.GPIO_RST_PIN = gpiozero.LED(self.RST_PIN)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 192, in __init__
    super().__init__(pin, active_high=active_high,
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 74, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/lgpio.py", line 126, in __init__
    lgpio.gpio_claim_input(
  File "/usr/lib/python3/dist-packages/lgpio.py", line 755, in gpio_claim_input
    return _u2i(_lgpio._gpio_claim_input(handle&0xffff, lFlags, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO busy'

**Comment by jayofelony** [comment]
Fixed in 2.8.7.2
