### ISSUE TITLE
#BUG

### ISSUE THREAD

**Issue by jojozada** [jayofelony/pwnagotchi#107]
Hello, I ask for help.
I'm having a bug in waveshare V4

In the new update V2.8.7.2

When the screen updates it keeps changing the background from black to white.
This occurs with each new frame update.

I'm using.

Screen: Waveshare V4, 2.13inch e-Paper HAT

Respberry OW

driver:
waveshare2in13b_v4

ISO 32bit

I tested several other versions but they are only working but with this bug

config.toml:

main.name = "ENIAC"
main.lang = "en"
ui.display.enabled = true
ui.display.type = "waveshare2in13b_v4"
ui.display.color = "Black"

**Comment by jayofelony** [comment]
Use waveshare_4 as display type

**Comment by jojozada** [comment]
waveshare_4  don't start the screen

**Comment by jayofelony** [comment]
Run `sudo pwnagotchi --debug` and look for any errors

**Comment by Atlant87** [comment]
I had same problem, everething been fine i correcting plugins coordinats and some label to specific symbols like heart in "age" plugin, and then sometging went bad. Pwnagotchi start rebooted cyclically, the screen periodically flickers from white to black. I removed 

`pi@10.0.0.2:~ $ sudo pwnagotchi --debug
DEBUG:root:[FS] Daemonized...
DEBUG:root:[FS] Syncing /var/tmp/pwnagotchi -> /run/pwnagotchi/disk/pwnagotchi
DEBUG:root:loading plugins from /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default - enabled: ['age', 'aircrackonly', 'auto-update', 'bt-tether', 'exp', 'fix_services', 'grid', 'internet-conection', 'logtail', 'memtemp-plus', 'powerutils', 'pwnmenu', 'session-stats', 'webcfg', 'wpa-sec']
[2024-03-22 22:47:48,135] [DEBUG] loading plugins from /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default - enabled: ['age', 'aircrackonly', 'auto-update', 'bt-tether', 'exp', 'fix_services', 'grid', 'internet-conection', 'logtail', 'memtemp-plus', 'powerutils', 'pwnmenu', 'session-stats', 'webcfg', 'wpa-sec']
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/session-stats.py
[2024-03-22 22:47:48,141] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/session-stats.py
DEBUG:root:loaded plugin session-stats as <session-stats.SessionStats object at 0x7fae5bf150>
[2024-03-22 22:47:48,162] [DEBUG] loaded plugin session-stats as <session-stats.SessionStats object at 0x7fae5bf150>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/webcfg.py
[2024-03-22 22:47:48,163] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/webcfg.py
DEBUG:root:loaded plugin webcfg as <webcfg.WebConfig object at 0x7fae5bfb50>
[2024-03-22 22:47:48,175] [DEBUG] loaded plugin webcfg as <webcfg.WebConfig object at 0x7fae5bfb50>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/fix_services.py
[2024-03-22 22:47:48,176] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/fix_services.py
DEBUG:root:loaded plugin fix_services as <fix_services.FixServices object at 0x7fae5d8a10>
[2024-03-22 22:47:48,199] [DEBUG] loaded plugin fix_services as <fix_services.FixServices object at 0x7fae5d8a10>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/logtail.py
[2024-03-22 22:47:48,200] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/logtail.py
DEBUG:root:loaded plugin logtail as <logtail.Logtail object at 0x7fae5d9d90>
[2024-03-22 22:47:48,238] [DEBUG] loaded plugin logtail as <logtail.Logtail object at 0x7fae5d9d90>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/grid.py
[2024-03-22 22:47:48,239] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/grid.py
DEBUG:root:loaded plugin grid as <grid.Grid object at 0x7fae5dabd0>
[2024-03-22 22:47:48,264] [DEBUG] loaded plugin grid as <grid.Grid object at 0x7fae5dabd0>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/wpa-sec.py
[2024-03-22 22:47:48,265] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/wpa-sec.py
DEBUG:root:loaded plugin wpa-sec as <wpa-sec.WpaSec object at 0x7fae5db490>
[2024-03-22 22:47:48,342] [DEBUG] loaded plugin wpa-sec as <wpa-sec.WpaSec object at 0x7fae5db490>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/bt-tether.py
[2024-03-22 22:47:48,344] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/bt-tether.py
DEBUG:root:loaded plugin bt-tether as <bt-tether.BTTether object at 0x7fae62d9d0>
[2024-03-22 22:47:48,553] [DEBUG] loaded plugin bt-tether as <bt-tether.BTTether object at 0x7fae62d9d0>
DEBUG:root:loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/auto-update.py
[2024-03-22 22:47:48,554] [DEBUG] loading /usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/auto-update.py
DEBUG:root:loaded plugin auto-update as <auto-update.AutoUpdate object at 0x7fae62ec50>
[2024-03-22 22:47:48,558] [DEBUG] loaded plugin auto-update as <auto-update.AutoUpdate object at 0x7fae62ec50>
DEBUG:root:loading plugins from /usr/local/share/pwnagotchi/custom-plugins/ - enabled: ['age', 'aircrackonly', 'auto-update', 'bt-tether', 'exp', 'fix_services', 'grid', 'internet-conection', 'logtail', 'memtemp-plus', 'powerutils', 'pwnmenu', 'session-stats', 'webcfg', 'wpa-sec']
[2024-03-22 22:47:48,559] [DEBUG] loading plugins from /usr/local/share/pwnagotchi/custom-plugins/ - enabled: ['age', 'aircrackonly', 'auto-update', 'bt-tether', 'exp', 'fix_services', 'grid', 'internet-conection', 'logtail', 'memtemp-plus', 'powerutils', 'pwnmenu', 'session-stats', 'webcfg', 'wpa-sec']
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/age.py
[2024-03-22 22:47:48,561] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/age.py
DEBUG:root:loaded plugin age as <age.Age object at 0x7fae62f9d0>
[2024-03-22 22:47:48,564] [DEBUG] loaded plugin age as <age.Age object at 0x7fae62f9d0>
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/memtemp-plus.py
[2024-03-22 22:47:48,566] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/memtemp-plus.py
DEBUG:root:loaded plugin memtemp-plus as <memtemp-plus.MemTempPlus object at 0x7fae638b50>
[2024-03-22 22:47:48,569] [DEBUG] loaded plugin memtemp-plus as <memtemp-plus.MemTempPlus object at 0x7fae638b50>
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/exp.py
[2024-03-22 22:47:48,571] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/exp.py
DEBUG:root:[EXP Plugin] Loading Exp
[2024-03-22 22:47:48,575] [DEBUG] [EXP Plugin] Loading Exp
DEBUG:root:loaded plugin exp as <exp.EXP object at 0x7fae63a790>
[2024-03-22 22:47:48,577] [DEBUG] loaded plugin exp as <exp.EXP object at 0x7fae63a790>
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/pwnmenu.py
[2024-03-22 22:47:48,579] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/pwnmenu.py
DEBUG:root:loaded plugin pwnmenu as <pwnmenu.PwnMenu object at 0x7fac6a9010>
[2024-03-22 22:47:48,637] [DEBUG] loaded plugin pwnmenu as <pwnmenu.PwnMenu object at 0x7fac6a9010>
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/internet-conection.py
[2024-03-22 22:47:48,638] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/internet-conection.py
DEBUG:root:loaded plugin internet-conection as <internet-conection.InternetConnectionPlugin object at 0x7fac6aa010>
[2024-03-22 22:47:48,643] [DEBUG] loaded plugin internet-conection as <internet-conection.InternetConnectionPlugin object at 0x7fac6aa010>
DEBUG:root:loading /usr/local/share/pwnagotchi/custom-plugins/aircrackonly.py
[2024-03-22 22:47:48,644] [DEBUG] loading /usr/local/share/pwnagotchi/custom-plugins/aircrackonly.py
DEBUG:root:loaded plugin aircrackonly as <aircrackonly.AircrackOnly object at 0x7fac6c0910>
[2024-03-22 22:47:48,651] [DEBUG] loaded plugin aircrackonly as <aircrackonly.AircrackOnly object at 0x7fac6c0910>
INFO:root:[Fix_Services] plugin loaded.
INFO:root:Logtail plugin loaded.
INFO:root:WPA_SEC: plugin loaded
[2024-03-22 22:47:48,657] [INFO] [Fix_Services] plugin loaded.
INFO:root:Internet Connection Plugin loaded.
[2024-03-22 22:47:48,659] [INFO] Logtail plugin loaded.
INFO:root:grid plugin loaded.
[2024-03-22 22:47:48,660] [INFO] WPA_SEC: plugin loaded
INFO:root:[update] plugin loaded.
[2024-03-22 22:47:48,661] [INFO] Internet Connection Plugin loaded.
[2024-03-22 22:47:48,662] [INFO] grid plugin loaded.
[2024-03-22 22:47:48,663] [INFO] [update] plugin loaded.
INFO:root:memtemp plugin loaded.
[2024-03-22 22:47:48,664] [INFO] memtemp plugin loaded.
INFO:root:webcfg: Plugin loaded.
INFO:root:Session-stats plugin loaded.
[2024-03-22 22:47:48,665] [INFO] webcfg: Plugin loaded.
INFO:root:aircrackonly plugin loaded
[2024-03-22 22:47:48,666] [INFO] Session-stats plugin loaded.
INFO:root:[EXP Plugin] Plugin Loaded
[2024-03-22 22:47:48,667] [INFO] aircrackonly plugin loaded
[2024-03-22 22:47:48,667] [INFO] [EXP Plugin] Plugin Loaded
INFO:root:Pwnmenu Plugin loaded.
DEBUG:root:INVERT BLACK/WHITES:True
[2024-03-22 22:47:48,668] [INFO] Pwnmenu Plugin loaded.
[2024-03-22 22:47:48,678] [DEBUG] INVERT BLACK/WHITES:True
Exception ignored in thread started by: <function locked_cb at 0x7fafedccc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/__init__.py", line 85, in locked_cb
    cb(*args, *kwargs)
  File "/usr/local/share/pwnagotchi/custom-plugins/pwnmenu.py", line 86, in on_loaded
    listener = Listener(address)
               ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 447, in __init__
    self._listener = SocketListener(address, family, backlog)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/connection.py", line 590, in __init__
    self._socket.bind(address)
OSError: [Errno 98] Address already in use
WARNING:root:ui.fps is 0, the display will only update for major changes
DEBUG:root:Got here
[2024-03-22 22:47:48,761] [WARNING] ui.fps is 0, the display will only update for major changes
INFO:root:initializing waveshare v2in13_V4 display
[2024-03-22 22:47:48,762] [DEBUG] Got here
[2024-03-22 22:47:48,770] [INFO] initializing waveshare v2in13_V4 display
INFO:root:BT-TETHER: Successfully loaded ...
[2024-03-22 22:47:48,877] [INFO] BT-TETHER: Successfully loaded ...
INFO:root:aircrackonly: Found aircrack-ng 1:1.7-5
[2024-03-22 22:47:48,878] [INFO] aircrackonly: Found aircrack-ng 1:1.7-5
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
          ~~~~~~~~~^^^^^^
KeyError: PinInfo(number=11, name='GPIO17', names=frozenset({17, 'J8:11', '17', 'GPIO17', 'WPI0', 'BOARD11', 'BCM17'}), pull='', row=6, col=1, interfaces=frozenset({'', 'uart', 'dpi', 'spi', 'gpio'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 338, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 318, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 240, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/waveshare2in13_V4.py", line 35, in initialize
    from pwnagotchi.ui.hw.libs.waveshare.v2in13_V4.epd2in13_V4 import EPD
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/v2in13_V4/epd2in13_V4.py", line 32, in <module>
    from .. import epdconfig
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/epdconfig.py", line 127, in <module>
    implementation = RaspberryPi()
                     ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/libs/waveshare/epdconfig.py", line 52, in __init__
    self.GPIO_RST_PIN = gpiozero.LED(self.RST_PIN)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 192, in __init__
    super().__init__(pin, active_high=active_high,
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 74, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gpiozero/pins/lgpio.py", line 126, in __init__
    lgpio.gpio_claim_input(
  File "/usr/lib/python3/dist-packages/lgpio.py", line 755, in gpio_claim_input
    return _u2i(_lgpio._gpio_claim_input(handle&0xffff, lFlags, gpio))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/lgpio.py", line 458, in _u2i
    raise error(error_text(v))
lgpio.error: 'GPIO busy'
`
