### ISSUE TITLE
[BUG] KeyError: 'color'

### ISSUE THREAD

**Issue by MattPlayGamez** [jayofelony/pwnagotchi#152]
**Describe the bug**
`pi@MP:~ $ sudo /usr/bin/pwnagotchi-launcher
INFO:root:webcfg: Plugin loaded.
[2024-05-09 20:36:16,885] [INFO] webcfg: Plugin loaded.
INFO:root:[Fix_Services] plugin loaded.
[2024-05-09 20:36:16,885] [INFO] [Fix_Services] plugin loaded.
INFO:root:grid plugin loaded.
INFO:root:[update] plugin loaded.
[2024-05-09 20:36:16,886] [INFO] grid plugin loaded.
INFO:root:Session-stats plugin loaded.
[2024-05-09 20:36:16,886] [INFO] [update] plugin loaded.
[2024-05-09 20:36:16,888] [INFO] Session-stats plugin loaded.
WARNING:root:ui.fps is 0, the display will only update for major changes
[2024-05-09 20:36:16,896] [WARNING] ui.fps is 0, the display will only update for major changes
INFO:root:initializing inky display
[2024-05-09 20:36:16,897] [INFO] initializing inky display
Traceback (most recent call last):
  File "/usr/local/bin/pwnagotchi", line 337, in <module>
    pwnagotchi_cli()
  File "/usr/local/bin/pwnagotchi", line 316, in pwnagotchi_cli
    display = Display(config=config, state={'name': '%s>' % pwnagotchi.name()})
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 18, in __init__
    self.init_display()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/display.py", line 279, in init_display
    self._implementation.initialize()
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/ui/hw/inky.py", line 36, in initialize
    if self.config['color'] == 'fastAndFurious':
       ~~~~~~~~~~~^^^^^^^^^
KeyError: 'color'
pi@MP:~ $`

**To Reproduce**
Start: `sudo /usr/bin/pwnagotchi-launcher`

**Expected behavior**
The program to run and execute

**Screenshots**
![image](https://github.com/jayofelony/pwnagotchi/assets/62027538/0a1d2e95-7ccf-4309-8b13-e7b7513af87b)

**Environment (please complete the following information):**
 - Pwnagotchi version: `2.8.9`
 - OS version `12`
 - Type of hardware: `rasberrypi 4B`

**Comment by MattPlayGamez** [comment]
Ok sorry
I was following a tutorial and it recommended me to use inkyphat even if i didn't have one.
Solved my issue by setting ui.display.enabled to false and commenting other ui.display things out
