### ISSUE TITLE
[BUG] bettercap version in grid.py errors with "list index out of range

### ISSUE THREAD

**Issue by JAKAMI99** [jayofelony/pwnagotchi#164]
**Describe the bug**

Running pwnagotchi in debug mode results in a "list index out of range error" since the version checks by "\n" (newlines), but output of "bettercap -version" is an onliner.

```
[2024-05-24 01:46:31,846] [DEBUG] list index out of range
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/plugins/default/grid.py", line 134, in on_internet_avail>
    grid.update_data(agent.last_session)
  File "/usr/local/lib/python3.11/dist-packages/pwnagotchi/grid.py", line 95, in update_data
    'bettercap': subprocess.getoutput("bettercap -version").split(".\n\n")[1],
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
```

**Comment by jayofelony** [comment]
I know, but it does show line breaks when sent to opwngrid.xyz, that what is there for.
